### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by x4rm** [evgeny-yanul/protractor#7]

**Comment by x4rm** [comment]
> вынести в utils дубликаты методов

https://github.com/evgeny-yanul/protractor/commit/1210bee16ce8e85856df082f9f499939901163b9

**Comment by x4rm** [comment]
> убрать из it импорты
var fs = require('fs');

> убрать из it хардкод из it
var path = 'c:/report.xlsx';

> убрать из it работу с низкоуровневыми библиотеками
fs.existsSync(path);

> убрать из it вещи вида
        browser.actions()
            .sendKeys(protractor.Key.ENTER)
            .sendKeys(protractor.Key.ARROW_DOWN)
            .sendKeys(protractor.Key.ENTER)
            .perform();

> убрать из it явные ожидания и их колбэки

https://github.com/evgeny-yanul/protractor/commit/43d28b4d6b222dcc8ff220d217fc657ccae4d84f

**Comment by x4rm** [comment]
> убрать комментарии над it,
добавить комментарии над методами и полями page object,
форматирование

https://github.com/evgeny-yanul/protractor/commit/98b28cda6ff3b8bd1989cfe5e58d3288bae2de8c
https://github.com/evgeny-yanul/protractor/commit/2d56bb7c05a2be201e04091c07317464b6ab2a3a

**Comment by x4rm** [comment]
> переписать в строку поля вида, исправить на обратное в методах
   that.hauptDate = element(by.css('.modal-content'))
        .all(by.model('dateItem')).first();
    that.warenDate = element(by.css('.modal-content'))
        .all(by.model('dateItem')).last();

https://github.com/evgeny-yanul/protractor/commit/9a8a8e20b529604cef135ba6c1ac41627c3eae03
https://github.com/evgeny-yanul/protractor/commit/4e4178d91a9a5164a1e1171b6962612e34bb99b1

**Comment by x4rm** [comment]
> реализовать через метод
   that.nod = element(by.tagName('body')).
        element(by.cssContainingText('.aciTreeText', '39, Frühling/Sommer 2015'));
    that.sub1 = element(by.tagName('body')).
        element(by.cssContainingText('.aciTreeText', 'Inszenierungspunkt'));
    that.sub2 = element(by.tagName('body')).
        element(by.cssContainingText('.aciTreeText', '3911 Schwarzpreis ET: 04.03.2016'));

https://github.com/evgeny-yanul/protractor/commit/4feab2cbe97f1369dcb0ae8911c1c096ce6b41eb

**Comment by x4rm** [comment]
> исправить названия переменных и методов

https://github.com/evgeny-yanul/protractor/commit/1efe820f27c35c58c909fb407f970f22f419e5d6

**Comment by x4rm** [comment]
> сменить имена файлов

https://github.com/evgeny-yanul/protractor/commit/905370b545adf231368dc53e77c86c72aa1ba0bd
https://github.com/evgeny-yanul/protractor/commit/fcb71c946cdd02161d227a2bc462fcbf2787401d

**Comment by x4rm** [comment]
>  переписать на использование методов elementa 
browser.actions().click(element).perform(); на element.click();
browser.actions().click(element)
                .sendKeys(protractor.Key.ARROW_UP)
                .sendKeys(protractor.Key.ENTER)
                .perform();

https://github.com/evgeny-yanul/protractor/commit/217ef1daa0bf2f631ed0decce67323ba512f2eae
https://github.com/evgeny-yanul/protractor/commit/728bfd70d866ceb88b4a73f9f25fc39ead34a40d

**Comment by x4rm** [comment]
> исправить beforeEach на beforeAll

https://github.com/evgeny-yanul/protractor/commit/4458600a03056c8e1c6f605f0b2a96424f9829d9

**Comment by x4rm** [comment]
> проверить необходимость. если они нужны, оставить методе
that.visibilityWaitingAndClick = function (element) {
        browser.wait(EC.visibilityOf(element), 8000);
        browser.actions().click(element).perform();
    };

https://github.com/evgeny-yanul/protractor/commit/c24413c387be3e9ab30a1eac57345b48ddcd17d6
https://github.com/evgeny-yanul/protractor/commit/d9ad8cc4bb593d361460c4b79f38786925f6920a
https://github.com/evgeny-yanul/protractor/commit/8eed4f4ea57af8f52619e84081db1844bebdb889

**Comment by x4rm** [comment]
> вынести из util.saveFile expect

https://github.com/evgeny-yanul/protractor/commit/17c7a10868d4bd0960c573d81d0202bc100dd238

**Comment by x4rm** [comment]
> вынести хардкод и таймаут в конфиг. второй можно в po

https://github.com/evgeny-yanul/protractor/commit/f4a3ca641eadf29ed64cda9e13e641d77af41826

**Comment by x4rm** [comment]
> установить относительные пути для загрузки файлов

https://github.com/evgeny-yanul/protractor/commit/1afdc15725dfd4946c358c94fe0242d1f7aa038f

**Comment by evgeny-yanul** [comment]
**Проблема с параметрами запуска**

> отключить кэш, убрать код для закрытия дерева элементов

**Comment by x4rm** [comment]
> добавить документацию jsDoc

https://github.com/evgeny-yanul/protractor/commit/d61358bc4fbf75d9ae5dfe730990ade570aff150

**Comment by x4rm** [comment]
> использовать библиотеку lodash для генерации числа

https://github.com/evgeny-yanul/protractor/commit/7003432110d6593f1973b502e1eab39ac670ef88

**Comment by x4rm** [comment]
> перенести из util в po специфичные для конкретной спеки методы

https://github.com/evgeny-yanul/protractor/commit/4213e58cc5ceda6e9a141cb120261a5530ddb8d6

**Comment by x4rm** [comment]
> переписать for на forEach

https://github.com/evgeny-yanul/protractor/commit/3aa1bce6cb8ff635753730a85eacc48f1529ccc1
https://github.com/evgeny-yanul/protractor/commit/41eb21a6100178531e18968704eea313d5b70073

**Comment by x4rm** [comment]
> добавить в browser.wait описание ошибок

https://github.com/evgeny-yanul/protractor/commit/6e976f5e4b4cdaec03eeb146d6fa5523d17341dd

**Comment by x4rm** [comment]
> экспортировать готовые po-объекты вместо конструкторов

https://github.com/evgeny-yanul/protractor/commit/959d572fd816a68758af1b18be563e24db5a5c89

**Comment by x4rm** [comment]
> везде кроме спек почейнить промисы явно

https://github.com/evgeny-yanul/protractor/commit/e025f55f7dfc3b0f4e9a65b0722da2c62a02449e
https://github.com/evgeny-yanul/protractor/commit/3be01ce3f0952c66511db624a2057dbbcdd779aa
https://github.com/evgeny-yanul/protractor/commit/f58b42f46ad5b525367a50b0f8e89e54465e5371
https://github.com/evgeny-yanul/protractor/commit/75c17feb5862fad46e1b1241b9fd000de6d6120e

**Comment by x4rm** [comment]
> вынести данные в переменные и в json

https://github.com/evgeny-yanul/protractor/commit/21ba17775cde036b09db2b53459827563e4d7a66

**Comment by x4rm** [comment]
> добавить в конфиг browser.baseUrl

https://github.com/evgeny-yanul/protractor/commit/f1aeaad49ad4bdc73efdd17a00f3a053f56ac3eb

**Comment by x4rm** [comment]
> переписать метод selectBranchInnerNode с учётом комментариев

https://github.com/evgeny-yanul/protractor/commit/73839bdb27f69b1c2deb85f2dbec4390589e1b51
https://github.com/evgeny-yanul/protractor/commit/47c6ccfa33f00101e0afb0e2ff15a1dc9eb763d8

**Comment by x4rm** [comment]
> переписать описывая компоненты вместо страниц.
убрать дубликаты из spec, po, data

https://github.com/evgeny-yanul/protractor/commit/b67818600e87892fe71e5abf8ebcb43de759ab2a
https://github.com/evgeny-yanul/protractor/commit/cc67d8989f4f51e21bddbed1663bf87c11abbc4b
https://github.com/evgeny-yanul/protractor/commit/72fc97bf55de91edc653edc1168c16b7bbb327d2
https://github.com/evgeny-yanul/protractor/commit/188dcd549310a18b7896be11d809e31463e541e3

**Comment by x4rm** [comment]
> разбить спеки и json lab2-3 на два файла

https://github.com/evgeny-yanul/protractor/commit/e4ae4133f1501164ff36af30735d1b7fafb183de

**Comment by x4rm** [comment]
> сменить названия спек и json-файлов в соответствии с тестируемым функционалом

https://github.com/evgeny-yanul/protractor/commit/db54da5103f861d3dbbefcdeace2d4dbc6697b50

**Comment by x4rm** [comment]
> выравнивание

https://github.com/evgeny-yanul/protractor/commit/445ebb304ab5e6dce0fa65b95b48fbbda54a7e77

**Comment by x4rm** [comment]
> forEach

https://github.com/evgeny-yanul/protractor/commit/88c12d005fb3380fbb6b98757ac23565ade2a0dd

**Comment by x4rm** [comment]
> название параметра c element

https://github.com/evgeny-yanul/protractor/commit/410bce73c601dff04930d71c8461d3b85ab624b1

**Comment by x4rm** [comment]
> поправить сообщения в descriptions и it

https://github.com/evgeny-yanul/protractor/commit/f0aeb4b776ad426d27ee06b2f0535b727ecab048

**Comment by x4rm** [comment]
> метод для menuElement

https://github.com/evgeny-yanul/protractor/commit/dcc7cfc84b835e0abf9685faa14108b66ca8d32a

**Comment by x4rm** [comment]
> метод для nodes

https://github.com/evgeny-yanul/protractor/commit/e6ded324e18da6d35d0b78c6d06e0caf55b56322

**Comment by x4rm** [comment]
> вынести в po методы из util

https://github.com/evgeny-yanul/protractor/commit/9272c07ed11475adc7e028e9f665f16cedb6a93d
https://github.com/evgeny-yanul/protractor/commit/341fa5c66ee969d16dd213487bfbd12e52056368

**Comment by x4rm** [comment]
> разбиение на po

https://github.com/evgeny-yanul/protractor/commit/0b41b5544d78fb768a22132d41f14faac6ef6b6d
https://github.com/evgeny-yanul/protractor/commit/1a76eca43f80dcafa524b9b6bf438a853fffcffc
https://github.com/evgeny-yanul/protractor/commit/88657a7bee2cf185df826d95e1221efdca641db3
https://github.com/evgeny-yanul/protractor/commit/0bcfc34139fce9da867bba14c1b9a4ebcb1ad07e

**Comment by x4rm** [comment]
> ошибки в чейнинге

https://github.com/evgeny-yanul/protractor/commit/2590392a4877f3c28e166b1a32bb95ec4053bf29

**Comment by x4rm** [comment]
> переписать setDropdownMenuValue

https://github.com/evgeny-yanul/protractor/commit/1fcf5f4793323482d37d6366b2c5206e4380bd29

**Comment by x4rm** [comment]
> добавить return в методах

https://github.com/evgeny-yanul/protractor/commit/4b7b8ef5b3b5aa5f97ce7ca121b10cf7a679cf31
https://github.com/evgeny-yanul/protractor/commit/4831fa9cd8d206d77547e627bc7fd7c89233a466

**Comment by x4rm** [comment]
> параметры в комментариях

https://github.com/evgeny-yanul/protractor/commit/0f8ccabc39dbdaaed6e8fad4f3e783f7e71871d2

**Comment by x4rm** [comment]
> вынести метод загрузки страницы в util

https://github.com/evgeny-yanul/protractor/commit/d52a31b07c56416a9c3e1e2bb1ff39f942f64818
https://github.com/evgeny-yanul/protractor/commit/cd76a22ce969419f813c920e88242a532f39e0a1

**Comment by x4rm** [comment]
> явное указание элемента, когда он не является единичным при выборке. исправить more than one element found for locator - the first result will be used

https://github.com/evgeny-yanul/protractor/commit/fe163a1a5819ec94c0b3253baca96d6a24b15c4b

**Comment by x4rm** [comment]
> избавиться от first-last в локаторах

https://github.com/evgeny-yanul/protractor/commit/09aba3c587df5c511e08fd4d48b4768247da146d
https://github.com/evgeny-yanul/protractor/commit/76002a4e585d7c4463d12e1df84a4c7a042157ac
https://github.com/evgeny-yanul/protractor/commit/10c6780e57335526593ca228888b150fed35daa7
https://github.com/evgeny-yanul/protractor/commit/d37b4095ae66d3b265eb7aa9237c45a351108941
https://github.com/evgeny-yanul/protractor/commit/81af5bd53d7e84fdcb5b282475a5b163ab77fd4d
https://github.com/evgeny-yanul/protractor/commit/ac14d24be8502570671d4901f24fa462311b4015
https://github.com/evgeny-yanul/protractor/commit/95d69323f4c4d45c6a08555d3456c4b0135399e0
https://github.com/evgeny-yanul/protractor/commit/c907f200bfa70cc9eb58f5edcc021b0997e10ec3

**Comment by x4rm** [comment]
> nodeKeys.sort().reverse();

https://github.com/evgeny-yanul/protractor/commit/d9cb6f1d11e2a589edeac95dc33c6370617956b1

**Comment by x4rm** [comment]
> rename po

https://github.com/evgeny-yanul/protractor/commit/9dce71886388836f8b68e38ca77e378063016998

**Comment by x4rm** [comment]
> remove button po

https://github.com/evgeny-yanul/protractor/commit/5ac3800c10790463b0b45c5f476ab85191e567a0

**Comment by x4rm** [comment]
> refactor dropdown setter

https://github.com/evgeny-yanul/protractor/commit/8855be36a1ace513856d7d9ae012c4668bb97a9c
https://github.com/evgeny-yanul/protractor/commit/0b92c974ff80014a10df161d834952821bf410a7
https://github.com/evgeny-yanul/protractor/commit/26276786c358a04bc3a24244e026636992d6fb8c
https://github.com/evgeny-yanul/protractor/commit/31bd8959cbb725167cef5bd27fd3fdc5467b0ce8

**Comment by x4rm** [comment]
> refactor input po

https://github.com/evgeny-yanul/protractor/commit/86eb20c7fac8d23e07862258a4d0af88a2c980ea

**Comment by x4rm** [comment]
> refactor open-close branch function

https://github.com/evgeny-yanul/protractor/commit/cc5972e8147d667566d150632c1e9a4c2453c126
https://github.com/evgeny-yanul/protractor/commit/eaa01bae81a333ea635fbfcc10eb47ff12cb8216

**Comment by x4rm** [comment]
> prototype inheritance

https://github.com/evgeny-yanul/protractor/commit/60ed4963dbf9bea8905dd211bed39c0619dccce9
https://github.com/evgeny-yanul/protractor/commit/bbd737518fc251134a32abda2b1a3245aae4bfdf

**Comment by x4rm** [comment]
> formatting

https://github.com/evgeny-yanul/protractor/commit/0e9482ca5919bdd1005655889f7a7fe7792f1866

**Comment by x4rm** [comment]
> refactor specs with setType, setPrice functions

https://github.com/evgeny-yanul/protractor/commit/325ee82b3bf163982fb0dded0d1a3f89cd0c24cd

**Comment by x4rm** [comment]
> refactor locator in publication data

https://github.com/evgeny-yanul/protractor/commit/895e0f6b468a78d3ce7e23a57d9bd4c581da5926

**Comment by x4rm** [comment]
> fix chaining

https://github.com/evgeny-yanul/protractor/commit/64723581890a8c83db91e1c9aa7728a07bf1ba2c
https://github.com/evgeny-yanul/protractor/commit/6208444af310b2dababc20fd1d87c91d38662449

**Comment by x4rm** [comment]
> add custom matcher

https://github.com/evgeny-yanul/protractor/commit/715f0116708158ac2beb61392f791973f5cb003a
